include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - input/**
    - build/**
    - .dart_tool/**

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    unawaited_futures: true
    always_declare_return_types: true
